services:
  - type: web
    name: your-app-name
    env: static
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install
      bun run build
    publishDir: dist